### ISSUE TITLE
Fatal error using PHPUnit 7.0.1

### ISSUE THREAD

**Issue by jaredcobb** [bobbingwide/wordpress-develop-tests#5]
When attempting to run `phpunit` while using PHPUnit 7.0.1 I'm getting the following error:

```
PHP Fatal error:  Class PHPUnit_Util_Test may not inherit from final class (PHPUnit\Util\Test) in /private/tmp/wordpress-tests-lib/includes/phpunit6-compat.php on line 18
```

- PHPUnit 7 was released on Feb 2nd 2018.
- PHP version being used is 7.1.14
- Cannot reproduce this error using PHPUnit 6.5.6

It appears they made this a `final` class in 7.x https://github.com/sebastianbergmann/phpunit/blob/7.0/src/Util/Test.php#L29

... Whereas in 6.x and earlier it was not https://github.com/sebastianbergmann/phpunit/blob/6.5/src/Util/Test.php#L32

**Comment by bobbingwide** [comment]
Hi, thanks for this. I'm only just geting around to looking at the problem. I'm going to upgrade the code to support PHPUnit 8. I'll leave this closed and raise a new issue.
